[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.0.0"
  # Aseg√∫rate de que estas variables coincidan con tu .env
  VITE_SUPABASE_URL = "https://lgxsfmvyjctxehwslvyw.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneHNmbXZ5amN0eGVod3Nsdnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTkyMTAsImV4cCI6MjA2ODM3NTIxMH0.s2DoNuKigl_G3erwGeC4oLCC_3UiMQu5KJd0gnnYDeU"
  VITE_APP_URL = "https://uplegal.netlify.app"
  VITE_MERCADOPAGO_PUBLIC_KEY = "APP_USR-63e03714-1aaa-4786-b174-3e151586115f"
  VITE_MERCADOPAGO_ACCESS_TOKEN = "APP_USR-5728750272037413-092708-793aa428f01c2a43948a6873b97f79ce-695874183"
  VITE_MERCADOPAGO_CLIENT_ID = "5728750272037413"
  VITE_MERCADOPAGO_CLIENT_SECRET = "CKS2UxC0su31Ff9aEh1vn8u6aYaXXP3Z"
  VITE_MERCADOPAGO_ENV = "production"
  VITE_SUPABASE_PROJECT_ID = "lgxsfmvyjctxehwslvyw"